# Generated by Django 4.2.28 on 2026-02-03 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FusionExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for vision-language analysis', upload_to='uploads/%Y/%m/%d/')),
                ('question', models.TextField(help_text='Enter your question about the image', max_length=1000)),
                ('fused_vector', models.TextField(blank=True, help_text='Quantum-fused embedding vector (JSON format)', null=True)),
                ('vision_analysis', models.TextField(blank=True, help_text='Vision analysis from LLaVA model', null=True)),
                ('ollama_answer', models.TextField(blank=True, help_text='Final reasoning answer from Mistral model', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fusion Experiment',
                'verbose_name_plural': 'Fusion Experiments',
                'ordering': ['-created_at'],
            },
        ),
    ]
