# Generated by Django 5.2.7 on 2026-02-03 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusionapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fusionexperiment',
            name='advanced_analysis',
            field=models.TextField(blank=True, help_text='Advanced vision analysis results (JSON format)', null=True),
        ),
        migrations.AddField(
            model_name='fusionexperiment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to=settings.AUTH_USER_MODEL),
        ),
    ]
